project:
  type: website

execute :
  freeze : auto
  
website:
  navbar:
    left:
      - href: index.qmd
        text: Le√ßon
      - href: introduction.qmd
        text: Page d'acceuil 
      - href: about.qmd
        text: Exercices

format:
  html:
    theme: cyborg 
    css: styles.css
    toc: true


